# アプリケーション共通のものを設定
server:
  port: 8090
  address: localhost

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    cache-enabled: false

spring:
  thymeleaf:
    cache: false
    mode: HTML
  datasource:
    hikari:
      connection-timeout: 15000
      maximum-pool-size: 3
      leak-detection-threshold: 5000
  devtools:
    livereload:
      enabled: false
  flyway:
    baseline-version: 1.0.0
    baseline-on-migrate: true
    locations:
      - classpath:/db/migration
